services:
  api:
    restart: always
    env_file:
      - .env
    ports:
      - "8888:8888"
    volumes:
      - .:/home/node/app
    build:
      context: .
      dockerfile: ./Dockerfile
    command: node dist/main.js
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: db
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
