services:
  - type: web
    name: kosmos-backend-api
    runtime: docker
    region: oregon
    plan: free
    branch: main
    healthCheckPath: /api/v1/health
    envVars:
      - key: NODE_ENV
        value: production

      - key: APP_NAME
        value: kosmos-backend-api

      - key: LOG_LEVEL
        value: http

      - key: LOG_TO_FILES
        value: false

      # URL Configuration
      - key: URLS_PROTOCOL
        value: https

      - key: URLS_URL
        value: kosmos-backend-api.onrender.com

      - key: URLS_PORT
        value: ''

      - key: URLS_API_ROOT
        value: ''

      # JWT
      - key: JWT_SECRET
        generateValue: true

      - key: JWT_EXPIRY_HOURS
        value: 48

      # Swagger
      - key: SWAGGER_ROUTE
        value: swagger

      - key: SWAGGER_USERNAME
        value: admin

      - key: SWAGGER_PASSWORD
        sync: false

      - key: SWAGGER_HAS_AUTH
        value: true

      # Database - Render conecta automáticamente
      - key: DATABASE_URL
        fromDatabase:
          name: kosmos-db
          property: connectionString

      # Email
      - key: EMAIL_FROM_ADDRESS
        value: noreply@kosmos.com

      - key: EMAIL_SMTP_HOST
        value: smtp.gmail.com

      - key: EMAIL_SMPT_PORT
        value: 587

      - key: EMAIL_SMTP_SECURE
        value: false

      - key: EMAIL_SMTP_USER
        sync: false

      - key: EMAIL_SMTP_PASS
        sync: false

      # Google OAuth
      - key: GOOGLE_CLIENT_ID
        sync: false

      - key: GOOGLE_CLIENT_SECRET
        sync: false

      # OAuth Redirects
      - key: OAUTH_SUCCESSFUL_REDIRECT
        value: https://tu-frontend.com/oauth/

      - key: OAUTH_FAIL_REDIRECT
        value: https://tu-frontend.com/

databases:
  - name: kosmos-db
    databaseName: kosmos_backend_api
    user: kosmos_user
    region: oregon
    plan: free
    ipAllowList: []
